### ISSUE TITLE
install on Android

### ISSUE THREAD

**Issue by fugo** [fluffymadness/pileMD-Mobile#1]
I use pileMD 0.9.0 (Ubuntu package) with  Linuxmint and like to try your mobile version. How can I use it?
I saw an .apk file in the .zip and installed it.
I selected a folder in ``/storage/emulated/0/Android/data/...`` but can't see my notes from Linux.
With a file manager I can see the .json files.

**Comment by MattNer0** [comment]
I think you need to use my fork of pilemd for the app.
It keeps your notes inside ".md" files instead of jsons (with folder structure as well)

**Comment by fugo** [comment]
Thank you
I will try this
